version: "3"

services:
  proxy:
    image: nginx:1.23
    ports: 
    - 80:80
    volumes:
    - ./proxy/nginx.conf:/etc/nginx/nginx.conf:ro
    - ./proxy/static:/etc/nginx/static
    depends_on:
      - backend

  backend:
    build: ./backend
    expose:
      - "3000"
    ports: 
      - 3000:3000